name: cms
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  custom_sliding_segmented_control: ^1.7.5
  dio: ^5.2.1+1
  email_validator: ^2.1.17
  expansion_tile_card: ^3.0.0
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  google_fonts: ^5.1.0
  http: ^1.0.0
  password_field_validator: ^0.0.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.11
   

dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:
  uses-material-design: true

  assets:
    - assets/images/