name: cms
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  http: ^1.0.0
  password_field_validator: ^0.0.1
   

dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:
  uses-material-design: true
